### ISSUE TITLE
the result is poor using FC7 feature to do face verification

### ISSUE THREAD

**Issue by IamMegatron2025** [wajihullahbaig/VGGFaceMatching#1]
hello, I use your `FeatureExtraction code` to do face verification for two face image. but the result is poor. can you give some advices?
here is my code:

```
from VGGFeatureExtractor import VGGExtractor
import os
import skimage
import numpy as np
import caffe
from scipy import spatial
import traceback
from numpy import *

if __name__ == '__main__':
    model_file = xxx/VGG_FACE_deploy.prototxt'
    pretrained_file = 'xxx/VGG_FACE.caffemodel'
    vggExtractor = VGGExtractor(model_file,pretrained_file)
    img1 = caffe.io.load_image('img1.jpg')
    img2 = caffe.io.load_image('img2.jpg')    
    
    feature1 = vggExtractor.GetFeature(img1)
    feature2 = vggExtractor.GetFeature(img2)
    vA=np.asarray(feature1['fc7'])
    vB=np.asarray(feature2['fc7'])
    cosine_distance=1-spatial.distance.cosine(vA,vB)
    print cosine_distance
```

the cosine_distance is often low even though the two test images are similar.

**Comment by wajihullahbaig** [comment]
Hi,
Can you ensure the image size you are using? Remember that VGG network is trained on 224x224 images. So your tests images must contains faces.

**Comment by IamMegatron2025** [comment]
@wajihullahbaig yes, my test images contain face and the face is the main part of images.

**Comment by wajihullahbaig** [comment]
@IvyGongoogle And they are color images? If so then the scores should be pretty high. Have you checked against two different images? Are the scores  still in the same range when you compare  the two identical images?

**Comment by IamMegatron2025** [comment]
@wajihullahbaig  sorry to reply so late. yes, they are color images. the score is very low for two different images. Maybe the faces in my images have big angle difference for two same images, and besides, it seems to have no alignment in your code.

**Comment by wajihullahbaig** [comment]
Well if that is the case of translations/rotations, the code wont handle such semantic changes.

**Comment by IamMegatron2025** [comment]
@wajihullahbaig thank your explanation.
